import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

interface ExerciseData {
  name: string;
  slug: string;
  description: string;
  movementPattern: string;
  plane: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  difficulty: string;
  difficultyScore: number;
  equipmentNeeded: string[];
  prerequisites: string[];
  contraindications: string[];
  tags: string[];
  progressionOf?: string;
  regressionOf?: string;
  formCues: string[];
  commonMistakes: string[];
}

const exercises: ExerciseData[] = [
  // ==================== PUSH EXERCISES ====================
  {
    name: "Wall Push-Up",
    slug: "wall-push-up",
    description: "A beginner-friendly push-up variation performed against a wall, great for building initial pushing strength.",
    movementPattern: "push",
    plane: "horizontal",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["anterior_deltoid", "core"],
    difficulty: "beginner",
    difficultyScore: 1,
    equipmentNeeded: [],
    prerequisites: [],
    contraindications: [],
    tags: ["push", "horizontal", "beginner_friendly"],
    regressionOf: "incline-push-up",
    formCues: ["Keep body straight", "Elbows at 45 degrees", "Full range of motion"],
    commonMistakes: ["Flaring elbows too wide", "Not going deep enough"],
  },
  {
    name: "Incline Push-Up",
    slug: "incline-push-up",
    description: "Push-up performed with hands elevated on a surface, reducing the load compared to floor push-ups.",
    movementPattern: "push",
    plane: "horizontal",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["anterior_deltoid", "core"],
    difficulty: "beginner",
    difficultyScore: 2,
    equipmentNeeded: [],
    prerequisites: ["10 wall push-ups"],
    contraindications: [],
    tags: ["push", "horizontal"],
    progressionOf: "wall-push-up",
    regressionOf: "push-up",
    formCues: ["Body forms straight line", "Lower chest to surface", "Push through palms"],
    commonMistakes: ["Sagging hips", "Looking up instead of neutral neck"],
  },
  {
    name: "Push-Up",
    slug: "push-up",
    description: "The fundamental pushing exercise. Builds chest, triceps, and core strength.",
    movementPattern: "push",
    plane: "horizontal",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["anterior_deltoid", "core"],
    difficulty: "beginner",
    difficultyScore: 3,
    equipmentNeeded: [],
    prerequisites: ["10 incline push-ups"],
    contraindications: [],
    tags: ["push", "horizontal"],
    progressionOf: "incline-push-up",
    regressionOf: "diamond-push-up",
    formCues: ["Hands shoulder-width apart", "Core tight throughout", "Chest touches floor"],
    commonMistakes: ["Flaring elbows 90 degrees", "Incomplete range of motion", "Sagging lower back"],
  },
  {
    name: "Diamond Push-Up",
    slug: "diamond-push-up",
    description: "Push-up with hands close together forming a diamond shape, emphasizing triceps.",
    movementPattern: "push",
    plane: "horizontal",
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["anterior_deltoid", "core"],
    difficulty: "intermediate",
    difficultyScore: 4,
    equipmentNeeded: [],
    prerequisites: ["20 push-ups"],
    contraindications: ["elbow"],
    tags: ["push", "horizontal", "close_grip_pushup"],
    progressionOf: "push-up",
    formCues: ["Thumbs and index fingers touch", "Elbows track close to body", "Lower chest to hands"],
    commonMistakes: ["Hands too far forward", "Elbows flaring out"],
  },
  {
    name: "Decline Push-Up",
    slug: "decline-push-up",
    description: "Push-up with feet elevated, increasing the load and targeting upper chest.",
    movementPattern: "push",
    plane: "horizontal",
    primaryMuscles: ["chest", "anterior_deltoid"],
    secondaryMuscles: ["triceps", "core"],
    difficulty: "intermediate",
    difficultyScore: 4,
    equipmentNeeded: [],
    prerequisites: ["20 push-ups"],
    contraindications: [],
    tags: ["push", "horizontal"],
    progressionOf: "push-up",
    formCues: ["Keep body straight from head to heels", "Control the descent", "Push explosively"],
    commonMistakes: ["Pike position instead of straight body", "Looking forward straining neck"],
  },
  {
    name: "Archer Push-Up",
    slug: "archer-push-up",
    description: "Wide push-up shifting weight to one arm, a progression toward one-arm push-up.",
    movementPattern: "push",
    plane: "horizontal",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["anterior_deltoid", "core"],
    difficulty: "intermediate",
    difficultyScore: 6,
    equipmentNeeded: [],
    prerequisites: ["30 push-ups"],
    contraindications: [],
    tags: ["push", "horizontal", "unilateral"],
    progressionOf: "push-up",
    regressionOf: "one-arm-push-up",
    formCues: ["Straight arm slides out", "Working arm does most of the work", "Keep hips level"],
    commonMistakes: ["Bending the straight arm", "Rotating torso too much"],
  },
  {
    name: "Pike Push-Up",
    slug: "pike-push-up",
    description: "Push-up in pike position targeting shoulders, a progression toward handstand push-up.",
    movementPattern: "push",
    plane: "vertical",
    primaryMuscles: ["shoulders", "triceps"],
    secondaryMuscles: ["chest", "core"],
    difficulty: "intermediate",
    difficultyScore: 5,
    equipmentNeeded: [],
    prerequisites: ["20 push-ups"],
    contraindications: ["shoulder"],
    tags: ["push", "vertical", "overhead_pressing"],
    regressionOf: "handstand-push-up",
    formCues: ["Hips high, forming inverted V", "Head moves forward past hands", "Lock out at top"],
    commonMistakes: ["Not enough hip elevation", "Rushing the movement"],
  },
  {
    name: "Handstand Push-Up",
    slug: "handstand-push-up",
    description: "Push-up performed in a handstand position against a wall. Advanced overhead pressing.",
    movementPattern: "push",
    plane: "vertical",
    primaryMuscles: ["shoulders", "triceps"],
    secondaryMuscles: ["chest", "core"],
    difficulty: "advanced",
    difficultyScore: 8,
    equipmentNeeded: [],
    prerequisites: ["30s wall handstand", "15 pike push-ups"],
    contraindications: ["shoulder", "wrist"],
    tags: ["push", "vertical", "overhead_pressing", "handstand_pushups", "wrist_extension_load"],
    progressionOf: "pike-push-up",
    formCues: ["Kick up to wall with control", "Head touches floor lightly", "Push straight up"],
    commonMistakes: ["Kipping or using momentum", "Head crashing to floor"],
  },
  {
    name: "Dips",
    slug: "dips",
    description: "Classic compound pushing exercise targeting chest and triceps.",
    movementPattern: "push",
    plane: "vertical",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["anterior_deltoid"],
    difficulty: "intermediate",
    difficultyScore: 5,
    equipmentNeeded: ["dip_station"],
    prerequisites: ["20 push-ups"],
    contraindications: ["shoulder", "elbow"],
    tags: ["push", "vertical", "dips"],
    formCues: ["Lean forward slightly for chest", "Lower until upper arms parallel", "Lock out at top"],
    commonMistakes: ["Going too deep too soon", "Flaring elbows", "Shrugging shoulders"],
  },
  {
    name: "Ring Dips",
    slug: "ring-dips",
    description: "Dips performed on gymnastic rings for increased instability and muscle activation.",
    movementPattern: "push",
    plane: "vertical",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["anterior_deltoid", "core"],
    difficulty: "advanced",
    difficultyScore: 7,
    equipmentNeeded: ["rings"],
    prerequisites: ["15 regular dips"],
    contraindications: ["shoulder", "elbow"],
    tags: ["push", "vertical", "dips", "rings"],
    progressionOf: "dips",
    formCues: ["Turn rings out at top (RTO)", "Control the rings throughout", "Maintain hollow body"],
    commonMistakes: ["Rings swinging wildly", "Partial range of motion"],
  },
  {
    name: "Ring Push-Up",
    slug: "ring-push-up",
    description: "Push-up on rings adding instability for greater muscle activation.",
    movementPattern: "push",
    plane: "horizontal",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["anterior_deltoid", "core"],
    difficulty: "intermediate",
    difficultyScore: 5,
    equipmentNeeded: ["rings"],
    prerequisites: ["20 push-ups"],
    contraindications: [],
    tags: ["push", "horizontal", "rings"],
    progressionOf: "push-up",
    formCues: ["Keep rings close to body", "Turn rings out at top", "Maintain tight core"],
    commonMistakes: ["Rings flaring out", "Rushing the movement"],
  },
  {
    name: "Pseudo Planche Push-Up",
    slug: "pseudo-planche-push-up",
    description: "Push-up with hands by hips and leaning forward, a planche progression.",
    movementPattern: "push",
    plane: "horizontal",
    primaryMuscles: ["chest", "anterior_deltoid"],
    secondaryMuscles: ["triceps", "core"],
    difficulty: "advanced",
    difficultyScore: 7,
    equipmentNeeded: [],
    prerequisites: ["30 push-ups", "30s plank"],
    contraindications: ["wrist", "shoulder"],
    tags: ["push", "horizontal", "planche_leans", "wrist_extension_load"],
    formCues: ["Hands by waist", "Lean forward significantly", "Protract shoulders at top"],
    commonMistakes: ["Hands too far forward", "Not enough lean"],
  },

  // ==================== PULL EXERCISES ====================
  {
    name: "Dead Hang",
    slug: "dead-hang",
    description: "Hanging from a bar with straight arms. Builds grip and shoulder mobility.",
    movementPattern: "pull",
    plane: "vertical",
    primaryMuscles: ["forearms", "lats"],
    secondaryMuscles: ["shoulders"],
    difficulty: "beginner",
    difficultyScore: 1,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: [],
    contraindications: [],
    tags: ["pull", "grip", "mobility"],
    formCues: ["Relax shoulders initially", "Grip firmly", "Breathe steadily"],
    commonMistakes: ["Gripping too loosely", "Holding breath"],
  },
  {
    name: "Active Hang",
    slug: "active-hang",
    description: "Hanging with engaged shoulders (depressed and retracted). Foundation for pull-ups.",
    movementPattern: "pull",
    plane: "vertical",
    primaryMuscles: ["lats", "shoulders"],
    secondaryMuscles: ["forearms", "core"],
    difficulty: "beginner",
    difficultyScore: 2,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["15s dead hang"],
    contraindications: [],
    tags: ["pull", "scapular"],
    progressionOf: "dead-hang",
    formCues: ["Pull shoulders down and back", "Chest up slightly", "Maintain tension"],
    commonMistakes: ["Shrugging shoulders", "Bending arms"],
  },
  {
    name: "Scapular Pull-Up",
    slug: "scapular-pull-up",
    description: "Pull-up focusing only on scapular movement. Essential for pull-up progression.",
    movementPattern: "pull",
    plane: "vertical",
    primaryMuscles: ["lats", "shoulders"],
    secondaryMuscles: ["biceps"],
    difficulty: "beginner",
    difficultyScore: 2,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["20s active hang"],
    contraindications: [],
    tags: ["pull", "scapular"],
    progressionOf: "active-hang",
    formCues: ["Keep arms straight", "Only move at shoulder blades", "Pull shoulders down"],
    commonMistakes: ["Bending elbows", "Using momentum"],
  },
  {
    name: "Australian Pull-Up",
    slug: "australian-pull-up",
    description: "Horizontal pulling exercise with feet on ground. Also known as inverted row.",
    movementPattern: "pull",
    plane: "horizontal",
    primaryMuscles: ["back", "biceps"],
    secondaryMuscles: ["rear_deltoid", "core"],
    difficulty: "beginner",
    difficultyScore: 3,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["10 scapular pull-ups"],
    contraindications: [],
    tags: ["pull", "horizontal", "rows"],
    regressionOf: "pull-up",
    formCues: ["Body straight from head to heels", "Pull chest to bar", "Squeeze shoulder blades"],
    commonMistakes: ["Hips sagging", "Not full range of motion"],
  },
  {
    name: "Negative Pull-Up",
    slug: "negative-pull-up",
    description: "Slow lowering phase of pull-up. Builds strength for full pull-ups.",
    movementPattern: "pull",
    plane: "vertical",
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["back", "forearms"],
    difficulty: "beginner",
    difficultyScore: 3,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["20s active hang", "10 australian pull-ups"],
    contraindications: [],
    tags: ["pull", "vertical", "eccentric"],
    regressionOf: "pull-up",
    formCues: ["Jump or step to top position", "Lower for 5+ seconds", "Control entire descent"],
    commonMistakes: ["Dropping too fast", "Not starting from full lockout at top"],
  },
  {
    name: "Pull-Up",
    slug: "pull-up",
    description: "The fundamental vertical pulling exercise. Pronated grip (palms facing away).",
    movementPattern: "pull",
    plane: "vertical",
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["back", "forearms", "core"],
    difficulty: "intermediate",
    difficultyScore: 5,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["5 negative pull-ups (5s each)"],
    contraindications: [],
    tags: ["pull", "vertical"],
    progressionOf: "negative-pull-up",
    formCues: ["Pull elbows to hips", "Chin over bar", "Full lockout at bottom"],
    commonMistakes: ["Kipping", "Half reps", "Excessive swinging"],
  },
  {
    name: "Chin-Up",
    slug: "chin-up",
    description: "Pull-up with supinated grip (palms facing you). More bicep emphasis.",
    movementPattern: "pull",
    plane: "vertical",
    primaryMuscles: ["biceps", "lats"],
    secondaryMuscles: ["back", "forearms"],
    difficulty: "intermediate",
    difficultyScore: 4,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["3 pull-ups"],
    contraindications: [],
    tags: ["pull", "vertical"],
    formCues: ["Supinated grip shoulder-width", "Pull chest to bar", "Control the negative"],
    commonMistakes: ["Partial range of motion", "Using momentum"],
  },
  {
    name: "Wide Grip Pull-Up",
    slug: "wide-grip-pull-up",
    description: "Pull-up with hands wider than shoulders. Emphasizes lat width.",
    movementPattern: "pull",
    plane: "vertical",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "back"],
    difficulty: "intermediate",
    difficultyScore: 6,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["10 pull-ups"],
    contraindications: ["shoulder"],
    tags: ["pull", "vertical", "wide_grip_pullup"],
    progressionOf: "pull-up",
    formCues: ["Hands 1.5x shoulder width", "Lead with chest", "Full range of motion"],
    commonMistakes: ["Going too wide", "Shrugging shoulders"],
  },
  {
    name: "Archer Pull-Up",
    slug: "archer-pull-up",
    description: "Pull-up shifting weight to one arm, progressing toward one-arm pull-up.",
    movementPattern: "pull",
    plane: "vertical",
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["back", "forearms"],
    difficulty: "advanced",
    difficultyScore: 7,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["15 pull-ups"],
    contraindications: [],
    tags: ["pull", "vertical", "unilateral"],
    progressionOf: "pull-up",
    formCues: ["One arm pulls, other extends", "Keep pulling arm close to body", "Control the movement"],
    commonMistakes: ["Both arms bending equally", "Using momentum"],
  },
  {
    name: "L-Sit Pull-Up",
    slug: "l-sit-pull-up",
    description: "Pull-up while holding an L-sit position. Combines pulling with core work.",
    movementPattern: "pull",
    plane: "vertical",
    primaryMuscles: ["lats", "biceps", "core"],
    secondaryMuscles: ["hip_flexors", "back"],
    difficulty: "advanced",
    difficultyScore: 7,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["10 pull-ups", "15s L-sit"],
    contraindications: [],
    tags: ["pull", "vertical", "l_sit_progression"],
    progressionOf: "pull-up",
    formCues: ["Maintain L-sit throughout", "Keep legs straight and parallel", "Pull chin over bar"],
    commonMistakes: ["Legs dropping during pull", "Bending knees"],
  },
  {
    name: "Muscle-Up",
    slug: "muscle-up",
    description: "Pulling movement transitioning to a dip above the bar. Advanced skill.",
    movementPattern: "pull",
    plane: "vertical",
    primaryMuscles: ["lats", "chest", "triceps"],
    secondaryMuscles: ["biceps", "anterior_deltoid", "core"],
    difficulty: "advanced",
    difficultyScore: 9,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["15 pull-ups", "15 dips"],
    contraindications: ["shoulder", "elbow"],
    tags: ["pull", "vertical", "skill", "muscle_up_training"],
    formCues: ["Explosive pull", "Lean forward at transition", "Fast transition is key"],
    commonMistakes: ["Not pulling high enough", "Chicken winging"],
  },
  {
    name: "Ring Row",
    slug: "ring-row",
    description: "Horizontal row using rings. Adjustable difficulty based on body angle.",
    movementPattern: "pull",
    plane: "horizontal",
    primaryMuscles: ["back", "biceps"],
    secondaryMuscles: ["rear_deltoid", "core"],
    difficulty: "beginner",
    difficultyScore: 2,
    equipmentNeeded: ["rings"],
    prerequisites: [],
    contraindications: [],
    tags: ["pull", "horizontal", "rows", "rings"],
    formCues: ["Body straight like a plank", "Pull rings to chest", "Squeeze shoulder blades"],
    commonMistakes: ["Hips sagging", "Pulling to stomach instead of chest"],
  },
  {
    name: "Front Lever Progression",
    slug: "front-lever-progression",
    description: "Tucked front lever hold. First step toward full front lever.",
    movementPattern: "pull",
    plane: "horizontal",
    primaryMuscles: ["lats", "core"],
    secondaryMuscles: ["biceps", "shoulders"],
    difficulty: "advanced",
    difficultyScore: 8,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["15 pull-ups", "30s hollow hold"],
    contraindications: ["lower_back"],
    tags: ["pull", "horizontal", "isometric", "front_lever_rows"],
    formCues: ["Tuck knees tight to chest", "Keep arms straight", "Depress shoulders"],
    commonMistakes: ["Bending arms", "Not engaging lats"],
  },

  // ==================== CORE EXERCISES ====================
  {
    name: "Plank",
    slug: "plank",
    description: "Fundamental isometric core exercise. Foundation for all calisthenics.",
    movementPattern: "core",
    plane: "sagittal",
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders", "glutes"],
    difficulty: "beginner",
    difficultyScore: 2,
    equipmentNeeded: [],
    prerequisites: [],
    contraindications: [],
    tags: ["core", "isometric"],
    formCues: ["Body straight from head to heels", "Squeeze glutes", "Don't let hips sag or pike"],
    commonMistakes: ["Hips too high", "Hips sagging", "Looking up"],
  },
  {
    name: "Side Plank",
    slug: "side-plank",
    description: "Lateral core stability exercise targeting obliques.",
    movementPattern: "core",
    plane: "transverse",
    primaryMuscles: ["obliques", "core"],
    secondaryMuscles: ["shoulders", "glutes"],
    difficulty: "beginner",
    difficultyScore: 3,
    equipmentNeeded: [],
    prerequisites: ["30s plank"],
    contraindications: [],
    tags: ["core", "isometric", "lateral"],
    formCues: ["Stack feet or stagger", "Hips off ground", "Body in straight line"],
    commonMistakes: ["Hips dropping", "Rotating forward or back"],
  },
  {
    name: "Hollow Body Hold",
    slug: "hollow-body-hold",
    description: "Gymnastic foundation position. Critical for many advanced skills.",
    movementPattern: "core",
    plane: "sagittal",
    primaryMuscles: ["core", "hip_flexors"],
    secondaryMuscles: ["quads"],
    difficulty: "beginner",
    difficultyScore: 3,
    equipmentNeeded: [],
    prerequisites: ["30s plank"],
    contraindications: ["lower_back"],
    tags: ["core", "isometric", "gymnastic"],
    formCues: ["Lower back pressed to floor", "Arms and legs extended", "Chin tucked"],
    commonMistakes: ["Lower back arching off floor", "Holding breath"],
  },
  {
    name: "Hollow Body Rock",
    slug: "hollow-body-rock",
    description: "Dynamic hollow body exercise rocking back and forth.",
    movementPattern: "core",
    plane: "sagittal",
    primaryMuscles: ["core", "hip_flexors"],
    secondaryMuscles: ["quads"],
    difficulty: "intermediate",
    difficultyScore: 4,
    equipmentNeeded: [],
    prerequisites: ["30s hollow body hold"],
    contraindications: ["lower_back"],
    tags: ["core", "dynamic", "gymnastic"],
    progressionOf: "hollow-body-hold",
    formCues: ["Maintain hollow position throughout", "Rock smoothly", "Don't break position"],
    commonMistakes: ["Breaking hollow position", "Using momentum from legs"],
  },
  {
    name: "L-Sit",
    slug: "l-sit",
    description: "Isometric hold with legs extended parallel to ground. Impressive core strength.",
    movementPattern: "core",
    plane: "sagittal",
    primaryMuscles: ["core", "hip_flexors"],
    secondaryMuscles: ["triceps", "quads"],
    difficulty: "intermediate",
    difficultyScore: 6,
    equipmentNeeded: [],
    prerequisites: ["30s hollow body hold", "30s support hold"],
    contraindications: ["lower_back"],
    tags: ["core", "isometric", "l_sit_progression"],
    formCues: ["Press shoulders down", "Keep legs straight and together", "Point toes"],
    commonMistakes: ["Bending knees", "Rounding lower back"],
  },
  {
    name: "Hanging Knee Raise",
    slug: "hanging-knee-raise",
    description: "Hanging core exercise bringing knees to chest.",
    movementPattern: "core",
    plane: "sagittal",
    primaryMuscles: ["core", "hip_flexors"],
    secondaryMuscles: ["forearms", "lats"],
    difficulty: "beginner",
    difficultyScore: 3,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["20s dead hang"],
    contraindications: [],
    tags: ["core", "dynamic", "hanging"],
    regressionOf: "hanging-leg-raise",
    formCues: ["Control the swing", "Bring knees to chest", "Lower with control"],
    commonMistakes: ["Excessive swinging", "Using momentum"],
  },
  {
    name: "Hanging Leg Raise",
    slug: "hanging-leg-raise",
    description: "Advanced hanging core exercise with straight legs.",
    movementPattern: "core",
    plane: "sagittal",
    primaryMuscles: ["core", "hip_flexors"],
    secondaryMuscles: ["forearms", "lats"],
    difficulty: "intermediate",
    difficultyScore: 5,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["15 hanging knee raises"],
    contraindications: ["lower_back"],
    tags: ["core", "dynamic", "hanging", "hanging_leg_raises"],
    progressionOf: "hanging-knee-raise",
    formCues: ["Keep legs straight", "Lift legs to bar if possible", "Control the descent"],
    commonMistakes: ["Bending knees", "Swinging"],
  },
  {
    name: "Dragon Flag",
    slug: "dragon-flag",
    description: "Advanced core exercise made famous by Bruce Lee.",
    movementPattern: "core",
    plane: "sagittal",
    primaryMuscles: ["core"],
    secondaryMuscles: ["lats", "hip_flexors"],
    difficulty: "advanced",
    difficultyScore: 8,
    equipmentNeeded: [],
    prerequisites: ["20 hanging leg raises", "60s hollow body hold"],
    contraindications: ["lower_back", "neck"],
    tags: ["core", "dynamic", "advanced"],
    formCues: ["Only shoulders touch bench", "Body straight like a flag", "Lower with control"],
    commonMistakes: ["Bending at hips", "Using momentum"],
  },
  {
    name: "Ab Wheel Rollout",
    slug: "ab-wheel-rollout",
    description: "Dynamic anti-extension core exercise using an ab wheel.",
    movementPattern: "core",
    plane: "sagittal",
    primaryMuscles: ["core"],
    secondaryMuscles: ["lats", "shoulders"],
    difficulty: "intermediate",
    difficultyScore: 5,
    equipmentNeeded: [],
    prerequisites: ["60s plank"],
    contraindications: ["lower_back"],
    tags: ["core", "dynamic", "anti_extension"],
    formCues: ["Keep core tight throughout", "Don't let hips sag", "Roll out as far as possible while maintaining form"],
    commonMistakes: ["Lower back arching", "Not going full range"],
  },

  // ==================== LEG EXERCISES ====================
  {
    name: "Bodyweight Squat",
    slug: "bodyweight-squat",
    description: "Fundamental lower body exercise. Foundation for all leg training.",
    movementPattern: "squat",
    plane: "sagittal",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    difficulty: "beginner",
    difficultyScore: 2,
    equipmentNeeded: [],
    prerequisites: [],
    contraindications: [],
    tags: ["legs", "squat"],
    formCues: ["Feet shoulder-width apart", "Knees track over toes", "Break parallel"],
    commonMistakes: ["Knees caving in", "Heels rising", "Not going deep enough"],
  },
  {
    name: "Squat Hold",
    slug: "squat-hold",
    description: "Isometric squat hold at bottom position. Great for mobility and strength.",
    movementPattern: "squat",
    plane: "sagittal",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core", "hip_flexors"],
    difficulty: "beginner",
    difficultyScore: 2,
    equipmentNeeded: [],
    prerequisites: [],
    contraindications: ["knee"],
    tags: ["legs", "squat", "isometric", "deep_squat"],
    formCues: ["Heels flat on ground", "Chest up", "Relax into position"],
    commonMistakes: ["Heels rising", "Rounding back"],
  },
  {
    name: "Bulgarian Split Squat",
    slug: "bulgarian-split-squat",
    description: "Single-leg squat with rear foot elevated. Great for leg strength and balance.",
    movementPattern: "squat",
    plane: "sagittal",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    difficulty: "intermediate",
    difficultyScore: 4,
    equipmentNeeded: [],
    prerequisites: ["20 bodyweight squats"],
    contraindications: ["knee"],
    tags: ["legs", "squat", "unilateral", "lunges"],
    formCues: ["Front shin vertical", "Back knee drops straight down", "Torso upright"],
    commonMistakes: ["Front knee tracking too far forward", "Leaning forward excessively"],
  },
  {
    name: "Shrimp Squat Progression",
    slug: "shrimp-squat-progression",
    description: "Single-leg squat holding back foot. Step toward shrimp squat.",
    movementPattern: "squat",
    plane: "sagittal",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    difficulty: "intermediate",
    difficultyScore: 6,
    equipmentNeeded: [],
    prerequisites: ["20 bulgarian split squats each leg"],
    contraindications: ["knee"],
    tags: ["legs", "squat", "unilateral"],
    regressionOf: "shrimp-squat",
    formCues: ["Hold back foot with hand", "Lower knee to ground", "Stay balanced"],
    commonMistakes: ["Falling forward", "Not controlling descent"],
  },
  {
    name: "Pistol Squat",
    slug: "pistol-squat",
    description: "Single-leg squat with non-working leg extended forward. Advanced leg exercise.",
    movementPattern: "squat",
    plane: "sagittal",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core", "hip_flexors"],
    difficulty: "advanced",
    difficultyScore: 7,
    equipmentNeeded: [],
    prerequisites: ["30 bodyweight squats", "Bulgarian split squats"],
    contraindications: ["knee", "ankle"],
    tags: ["legs", "squat", "unilateral", "pistol_squat", "single_leg_squat"],
    formCues: ["Keep free leg straight and forward", "Arms for counterbalance", "Full depth"],
    commonMistakes: ["Falling backward", "Knee caving in", "Not reaching full depth"],
  },
  {
    name: "Nordic Curl",
    slug: "nordic-curl",
    description: "Eccentric hamstring exercise. One of the best hamstring developers.",
    movementPattern: "hinge",
    plane: "sagittal",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "calves"],
    difficulty: "advanced",
    difficultyScore: 7,
    equipmentNeeded: [],
    prerequisites: [],
    contraindications: ["knee"],
    tags: ["legs", "hinge", "eccentric"],
    formCues: ["Anchor feet securely", "Lower body slowly", "Keep hips extended"],
    commonMistakes: ["Bending at hips", "Falling too fast"],
  },
  {
    name: "Glute Bridge",
    slug: "glute-bridge",
    description: "Hip extension exercise targeting glutes. Foundation for hip hinge patterns.",
    movementPattern: "hinge",
    plane: "sagittal",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    difficulty: "beginner",
    difficultyScore: 1,
    equipmentNeeded: [],
    prerequisites: [],
    contraindications: [],
    tags: ["legs", "hinge", "glutes"],
    formCues: ["Drive through heels", "Squeeze glutes at top", "Don't hyperextend lower back"],
    commonMistakes: ["Overarching lower back", "Not squeezing glutes"],
  },
  {
    name: "Single Leg Glute Bridge",
    slug: "single-leg-glute-bridge",
    description: "Unilateral hip extension for balanced glute development.",
    movementPattern: "hinge",
    plane: "sagittal",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    difficulty: "beginner",
    difficultyScore: 3,
    equipmentNeeded: [],
    prerequisites: ["20 glute bridges"],
    contraindications: [],
    tags: ["legs", "hinge", "unilateral", "glutes"],
    progressionOf: "glute-bridge",
    formCues: ["Keep hips level", "Extend non-working leg", "Drive through working heel"],
    commonMistakes: ["Hips rotating", "Using momentum"],
  },
  {
    name: "Calf Raise",
    slug: "calf-raise",
    description: "Standing calf exercise for lower leg development.",
    movementPattern: "squat",
    plane: "sagittal",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    difficulty: "beginner",
    difficultyScore: 1,
    equipmentNeeded: [],
    prerequisites: [],
    contraindications: [],
    tags: ["legs", "calves"],
    formCues: ["Full range of motion", "Pause at top", "Control the negative"],
    commonMistakes: ["Bouncing", "Partial range of motion"],
  },
  {
    name: "Single Leg Calf Raise",
    slug: "single-leg-calf-raise",
    description: "Unilateral calf raise for strength and balance.",
    movementPattern: "squat",
    plane: "sagittal",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    difficulty: "beginner",
    difficultyScore: 3,
    equipmentNeeded: [],
    prerequisites: ["20 calf raises"],
    contraindications: ["ankle"],
    tags: ["legs", "calves", "unilateral", "calf_raises_heavy"],
    progressionOf: "calf-raise",
    formCues: ["Hold wall for balance if needed", "Full range of motion", "Control the movement"],
    commonMistakes: ["Using momentum", "Not full range"],
  },

  // ==================== SKILL/MOBILITY EXERCISES ====================
  {
    name: "Wall Handstand",
    slug: "wall-handstand",
    description: "Handstand against wall. Foundation for freestanding handstand.",
    movementPattern: "push",
    plane: "vertical",
    primaryMuscles: ["shoulders", "core"],
    secondaryMuscles: ["triceps", "forearms"],
    difficulty: "intermediate",
    difficultyScore: 4,
    equipmentNeeded: [],
    prerequisites: ["30s plank", "15 pike push-ups"],
    contraindications: ["wrist", "shoulder"],
    tags: ["skill", "handstand", "isometric", "wrist_extension_load"],
    formCues: ["Chest to wall position", "Push through shoulders", "Keep body tight"],
    commonMistakes: ["Banana back", "Not pushing through shoulders"],
  },
  {
    name: "Crow Pose",
    slug: "crow-pose",
    description: "Arm balance with knees on backs of arms. Intro to hand balancing.",
    movementPattern: "push",
    plane: "horizontal",
    primaryMuscles: ["shoulders", "core"],
    secondaryMuscles: ["triceps", "chest"],
    difficulty: "intermediate",
    difficultyScore: 4,
    equipmentNeeded: [],
    prerequisites: ["30s plank"],
    contraindications: ["wrist"],
    tags: ["skill", "balance", "wrist_extension_load"],
    formCues: ["Knees high on arms", "Round upper back", "Look slightly forward"],
    commonMistakes: ["Not leaning forward enough", "Knees too low on arms"],
  },
  {
    name: "Support Hold",
    slug: "support-hold",
    description: "Straight arm support position on parallettes or dip bars.",
    movementPattern: "push",
    plane: "vertical",
    primaryMuscles: ["triceps", "shoulders"],
    secondaryMuscles: ["chest", "core"],
    difficulty: "beginner",
    difficultyScore: 2,
    equipmentNeeded: ["dip_station"],
    prerequisites: [],
    contraindications: [],
    tags: ["skill", "isometric", "support"],
    formCues: ["Depress shoulders", "Lock out arms", "Slight forward lean"],
    commonMistakes: ["Shrugging shoulders", "Bent arms"],
  },
  {
    name: "Ring Support Hold",
    slug: "ring-support-hold",
    description: "Support position on rings with rings turned out.",
    movementPattern: "push",
    plane: "vertical",
    primaryMuscles: ["triceps", "shoulders", "chest"],
    secondaryMuscles: ["core"],
    difficulty: "intermediate",
    difficultyScore: 4,
    equipmentNeeded: ["rings"],
    prerequisites: ["30s support hold"],
    contraindications: [],
    tags: ["skill", "isometric", "rings", "support"],
    progressionOf: "support-hold",
    formCues: ["Turn rings out (RTO)", "Depress shoulders", "Keep core tight"],
    commonMistakes: ["Rings turning in", "Bent arms"],
  },
  {
    name: "Skin the Cat",
    slug: "skin-the-cat",
    description: "Full rotation on rings or bar through German hang. Great for shoulder mobility.",
    movementPattern: "pull",
    plane: "vertical",
    primaryMuscles: ["shoulders", "lats"],
    secondaryMuscles: ["core", "biceps"],
    difficulty: "intermediate",
    difficultyScore: 5,
    equipmentNeeded: ["pull_up_bar"],
    prerequisites: ["5 pull-ups", "Good shoulder mobility"],
    contraindications: ["shoulder"],
    tags: ["skill", "mobility", "skin_the_cat"],
    formCues: ["Tuck knees to chest", "Rotate slowly through", "Control entire movement"],
    commonMistakes: ["Going too fast", "Insufficient shoulder mobility"],
  },

  // ==================== WARMUP/MOBILITY ====================
  {
    name: "Arm Circles",
    slug: "arm-circles",
    description: "Dynamic shoulder warm-up moving arms in circles.",
    movementPattern: "rotation",
    plane: "transverse",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    difficulty: "beginner",
    difficultyScore: 1,
    equipmentNeeded: [],
    prerequisites: [],
    contraindications: [],
    tags: ["warmup", "mobility", "shoulders"],
    formCues: ["Start small, gradually increase", "Keep arms straight", "Both directions"],
    commonMistakes: ["Moving too fast", "Not full range"],
  },
  {
    name: "Cat-Cow Stretch",
    slug: "cat-cow",
    description: "Spinal mobility exercise alternating between flexion and extension.",
    movementPattern: "core",
    plane: "sagittal",
    primaryMuscles: ["core", "back"],
    secondaryMuscles: [],
    difficulty: "beginner",
    difficultyScore: 1,
    equipmentNeeded: [],
    prerequisites: [],
    contraindications: [],
    tags: ["warmup", "mobility", "spine"],
    formCues: ["Move slowly and controlled", "Breathe with movement", "Full range of motion"],
    commonMistakes: ["Moving too fast", "Not coordinating breath"],
  },
  {
    name: "World's Greatest Stretch",
    slug: "worlds-greatest-stretch",
    description: "Comprehensive mobility drill hitting hips, hamstrings, and thoracic spine.",
    movementPattern: "hinge",
    plane: "sagittal",
    primaryMuscles: ["hip_flexors", "hamstrings"],
    secondaryMuscles: ["glutes", "back"],
    difficulty: "beginner",
    difficultyScore: 2,
    equipmentNeeded: [],
    prerequisites: [],
    contraindications: [],
    tags: ["warmup", "mobility", "full_body"],
    formCues: ["Deep lunge position", "Rotate thoracic spine", "Keep back knee off ground"],
    commonMistakes: ["Rushing through", "Limited rotation"],
  },
  {
    name: "Scapular Push-Up",
    slug: "scapular-push-up",
    description: "Push-up focusing only on scapular movement. Great for shoulder health.",
    movementPattern: "push",
    plane: "horizontal",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["core"],
    difficulty: "beginner",
    difficultyScore: 2,
    equipmentNeeded: [],
    prerequisites: [],
    contraindications: [],
    tags: ["warmup", "scapular", "shoulder_health"],
    formCues: ["Arms stay straight", "Only shoulder blades move", "Protract and retract fully"],
    commonMistakes: ["Bending arms", "Moving too fast"],
  },
  {
    name: "Band Pull-Apart",
    slug: "band-pull-apart",
    description: "Resistance band exercise for rear delts and upper back.",
    movementPattern: "pull",
    plane: "horizontal",
    primaryMuscles: ["rear_deltoid", "back"],
    secondaryMuscles: ["shoulders"],
    difficulty: "beginner",
    difficultyScore: 1,
    equipmentNeeded: ["resistance_bands"],
    prerequisites: [],
    contraindications: [],
    tags: ["warmup", "shoulder_health", "rear_delts"],
    formCues: ["Arms straight throughout", "Squeeze shoulder blades", "Control the return"],
    commonMistakes: ["Bending elbows", "Shrugging shoulders"],
  },
];

async function main() {
  console.log("Starting seed...");

  // Clear existing data
  await prisma.exerciseTag.deleteMany();
  await prisma.exerciseMuscle.deleteMany();
  await prisma.exerciseLibrary.deleteMany();

  console.log("Cleared existing exercise data");

  // Seed exercises
  for (const exercise of exercises) {
    const created = await prisma.exerciseLibrary.create({
      data: {
        name: exercise.name,
        slug: exercise.slug,
        description: exercise.description,
        movementPattern: exercise.movementPattern,
        plane: exercise.plane,
        primaryMuscles: JSON.stringify(exercise.primaryMuscles),
        secondaryMuscles: JSON.stringify(exercise.secondaryMuscles),
        difficulty: exercise.difficulty,
        difficultyScore: exercise.difficultyScore,
        equipmentNeeded: JSON.stringify(exercise.equipmentNeeded),
        prerequisites: JSON.stringify(exercise.prerequisites),
        contraindications: JSON.stringify(exercise.contraindications),
        progressionOf: exercise.progressionOf,
        regressionOf: exercise.regressionOf,
        formCues: JSON.stringify(exercise.formCues),
        commonMistakes: JSON.stringify(exercise.commonMistakes),
      },
    });

    // Create tags
    for (const tag of exercise.tags) {
      await prisma.exerciseTag.create({
        data: {
          exerciseId: created.id,
          tag,
        },
      });
    }

    // Create muscle entries
    for (const muscle of exercise.primaryMuscles) {
      await prisma.exerciseMuscle.create({
        data: {
          exerciseId: created.id,
          muscle,
          isPrimary: true,
        },
      });
    }

    for (const muscle of exercise.secondaryMuscles) {
      await prisma.exerciseMuscle.create({
        data: {
          exerciseId: created.id,
          muscle,
          isPrimary: false,
        },
      });
    }

    console.log(`Created exercise: ${exercise.name}`);
  }

  console.log(`Seeded ${exercises.length} exercises`);
  console.log("Seed completed!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

