import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Medical Disclaimer - CalisAI",
  description: "Medical and Fitness Disclaimer for CalisAI - AI Calisthenics Coach",
};

export default function DisclaimerPage() {
  return (
    <article className="prose prose-invert prose-emerald max-w-none">
      <h1 className="text-4xl font-display font-medium text-white mb-2">Medical & Fitness Disclaimer</h1>
      <p className="text-slate-400 text-lg mb-8">Last updated: January 2025</p>

      <div className="bg-red-500/10 border border-red-500/20 rounded-xl p-6 my-8">
        <p className="text-red-300 font-medium mb-2">⚠️ Important: Please Read Carefully</p>
        <p className="text-slate-300 leading-relaxed">
          The information provided by CalisAI is for general informational and educational purposes only. 
          It is not intended to be a substitute for professional medical advice, diagnosis, or treatment.
        </p>
      </div>

      <section className="space-y-6">
        <div>
          <h2 className="text-2xl font-display font-medium text-white mt-12 mb-4">Not Medical Advice</h2>
          <p className="text-slate-400 leading-relaxed">
            CalisAI is a fitness application that uses artificial intelligence to generate workout suggestions. 
            The content provided, including but not limited to workout plans, exercise recommendations, 
            nutrition guidance, and AI coach responses:
          </p>
          <ul className="list-disc list-inside text-slate-400 mt-4 space-y-2">
            <li>Is NOT medical advice and should not be treated as such</li>
            <li>Is NOT a substitute for consultation with qualified healthcare professionals</li>
            <li>Is generated by AI and may contain errors or inaccuracies</li>
            <li>May not be appropriate for your specific health situation</li>
          </ul>
        </div>

        <div>
          <h2 className="text-2xl font-display font-medium text-white mt-12 mb-4">Consult Your Doctor</h2>
          <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-xl p-6 my-6">
            <p className="text-slate-300 leading-relaxed">
              <strong className="text-yellow-300">Before starting any exercise program</strong>, especially if you:
            </p>
            <ul className="list-disc list-inside text-slate-400 mt-4 space-y-2">
              <li>Have any pre-existing medical conditions</li>
              <li>Have a history of heart disease, high blood pressure, or other cardiovascular issues</li>
              <li>Have joint problems, chronic pain, or previous injuries</li>
              <li>Are pregnant or nursing</li>
              <li>Are over 40 and have been inactive</li>
              <li>Have any concerns about your physical health</li>
            </ul>
            <p className="text-slate-300 leading-relaxed mt-4">
              You should consult with a qualified physician or healthcare provider.
            </p>
          </div>
        </div>

        <div>
          <h2 className="text-2xl font-display font-medium text-white mt-12 mb-4">Assumption of Risk</h2>
          <p className="text-slate-400 leading-relaxed">
            By using CalisAI, you acknowledge and agree that:
          </p>
          <ul className="list-disc list-inside text-slate-400 mt-4 space-y-2">
            <li>Physical exercise carries inherent risks of injury, including serious injury or death</li>
            <li>You are voluntarily participating in physical activities at your own risk</li>
            <li>You are solely responsible for determining whether any exercise is appropriate for you</li>
            <li>You should stop immediately if you experience pain, dizziness, or discomfort</li>
            <li>CalisAI is not responsible for any injuries that may result from using the Service</li>
          </ul>
        </div>

        <div>
          <h2 className="text-2xl font-display font-medium text-white mt-12 mb-4">Nutrition Disclaimer</h2>
          <p className="text-slate-400 leading-relaxed">
            Any nutritional information or diet guidance provided by CalisAI:
          </p>
          <ul className="list-disc list-inside text-slate-400 mt-4 space-y-2">
            <li>Is general information only and not personalized medical nutrition therapy</li>
            <li>Should not be used to diagnose or treat any medical condition</li>
            <li>May not account for food allergies, intolerances, or drug interactions</li>
            <li>Is not provided by a registered dietitian or licensed nutritionist</li>
          </ul>
          <p className="text-slate-400 leading-relaxed mt-4">
            If you have specific dietary needs, food allergies, eating disorders, or medical conditions 
            requiring specialized nutrition, please consult a registered dietitian or healthcare provider.
          </p>
        </div>

        <div>
          <h2 className="text-2xl font-display font-medium text-white mt-12 mb-4">AI Limitations</h2>
          <p className="text-slate-400 leading-relaxed">
            CalisAI uses artificial intelligence to generate recommendations. You should be aware that:
          </p>
          <ul className="list-disc list-inside text-slate-400 mt-4 space-y-2">
            <li>AI-generated content may contain errors or inaccuracies</li>
            <li>The AI cannot perform physical assessments or medical examinations</li>
            <li>Recommendations are based on the information you provide, which may be incomplete</li>
            <li>The AI cannot account for all individual variations and circumstances</li>
            <li>AI technology is not a replacement for human professional judgment</li>
          </ul>
        </div>

        <div>
          <h2 className="text-2xl font-display font-medium text-white mt-12 mb-4">Injury Prevention</h2>
          <p className="text-slate-400 leading-relaxed">
            To minimize the risk of injury while using CalisAI:
          </p>
          <ul className="list-disc list-inside text-slate-400 mt-4 space-y-2">
            <li>Always warm up properly before exercising</li>
            <li>Use proper form and technique for all exercises</li>
            <li>Progress gradually and don&apos;t rush to advanced movements</li>
            <li>Listen to your body and rest when needed</li>
            <li>Stop immediately if you experience sharp pain</li>
            <li>Consider working with a certified personal trainer in person</li>
          </ul>
        </div>

        <div>
          <h2 className="text-2xl font-display font-medium text-white mt-12 mb-4">No Guarantee of Results</h2>
          <p className="text-slate-400 leading-relaxed">
            CalisAI does not guarantee any specific results. Individual results vary based on many factors 
            including genetics, consistency, effort, nutrition, sleep, and other lifestyle factors. 
            Testimonials and examples are not guarantees of similar results.
          </p>
        </div>

        <div>
          <h2 className="text-2xl font-display font-medium text-white mt-12 mb-4">Limitation of Liability</h2>
          <p className="text-slate-400 leading-relaxed">
            To the fullest extent permitted by applicable law, CalisAI and its affiliates shall not be 
            liable for any direct, indirect, incidental, special, consequential, or punitive damages, 
            including but not limited to personal injury, arising out of or related to your use of the Service.
          </p>
        </div>

        <div>
          <h2 className="text-2xl font-display font-medium text-white mt-12 mb-4">Questions or Concerns</h2>
          <p className="text-slate-400 leading-relaxed">
            If you have any questions about this disclaimer, please contact us at{" "}
            <a href="mailto:support@calisai.com" className="text-emerald-400 hover:text-emerald-300">
              support@calisai.com
            </a>
          </p>
        </div>

        <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-xl p-6 my-8">
          <p className="text-emerald-300 font-medium mb-2">💪 Train Smart, Train Safe</p>
          <p className="text-slate-300 leading-relaxed">
            CalisAI is here to support your fitness journey, but your health and safety come first. 
            When in doubt, always consult a healthcare professional.
          </p>
        </div>
      </section>
    </article>
  );
}

